name: deployment qa

on: 
  push:
    branches:
      - feature/slack
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_STATUS: 'STARTED'
      COLOR: '#FFFF00'
    steps:
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |
          npm install
          npm run build

  deploy:
    name: Deploy Node.js app to AWS
    runs-on: ubuntu-latest
    env:
      NAME_BUCKET: hola
    steps:
      - name: Slack notification - Start
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GithubActions # Optional. (defaults to webhook app)
          SLACK_CHANNEL: deployments # Optional. (defaults to webhook)
          SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
          SLACK_CUSTOM_PAYLOAD: '{"attachments": [{"text": " *${{ env.JOB_STATUS }} : * \n Repo : https://github.com/${{ github.repository }} \n Branch : ${{ github.ref }} \n Commit message : ${{ github.event.head_commit.message }}","color": "${{ env.COLOR }}"}]}'
          # SLACK_CUSTOM_PAYLOAD: '{"attachments": [{"text": "Started And here’s an attachment!  \n s","color": "#7CD197"}]}'
        uses: Ilshidur/action-slack@master
      - name: Clone repository
        uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          ls
          ls
          ls
          sh .github/workflows/status.sh
          echo "${{ env.NAME_BUCKET }}"
      - name: Set Color Failure - Slack
        if: failure()
        run: |
          echo "::set-env name=JOB_STATUS::FAILURE"
          echo "::set-env name=COLOR::#FF0000"
      - name: Set Color Success - Slack
        if: success()
        run: |
          echo "::set-env name=COLOR::#7CD197"
          echo "::set-env name=JOB_STATUS::SUCCESSFUL" 
      - name: Slack notification - Status
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GithubActions 
          SLACK_CHANNEL: deployments 
          SLACK_AVATAR: repository 
          SLACK_CUSTOM_PAYLOAD: '{"attachments": [{"text": " *${{ env.JOB_STATUS }} : * \n Endpoint : https://www.google.com \n Repo : https://github.com/${{ github.repository }} \n Branch : ${{ github.ref }} \n Commit message : ${{ github.event.head_commit.message }}","color": "${{ env.COLOR }}" }]}'
        uses: Ilshidur/action-slack@master